/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRedacaoRouteImport } from './routes/app.redacao'
import { Route as AppPlanoRouteImport } from './routes/app.plano'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppCronogramaRouteImport } from './routes/app.cronograma'
import { Route as AppSimuladosIndexRouteImport } from './routes/app.simulados.index'
import { Route as AppMateriasIndexRouteImport } from './routes/app.materias.index'
import { Route as AppSimuladosAttemptIdRouteImport } from './routes/app.simulados.$attemptId'
import { Route as AppMateriasSlugRouteImport } from './routes/app.materias.$slug'
import { Route as AppSimuladosAttemptIdResultadoRouteImport } from './routes/app.simulados.$attemptId.resultado'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRedacaoRoute = AppRedacaoRouteImport.update({
  id: '/redacao',
  path: '/redacao',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanoRoute = AppPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppCronogramaRoute = AppCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AppRoute,
} as any)
const AppSimuladosIndexRoute = AppSimuladosIndexRouteImport.update({
  id: '/simulados/',
  path: '/simulados/',
  getParentRoute: () => AppRoute,
} as any)
const AppMateriasIndexRoute = AppMateriasIndexRouteImport.update({
  id: '/materias/',
  path: '/materias/',
  getParentRoute: () => AppRoute,
} as any)
const AppSimuladosAttemptIdRoute = AppSimuladosAttemptIdRouteImport.update({
  id: '/simulados/$attemptId',
  path: '/simulados/$attemptId',
  getParentRoute: () => AppRoute,
} as any)
const AppMateriasSlugRoute = AppMateriasSlugRouteImport.update({
  id: '/materias/$slug',
  path: '/materias/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppSimuladosAttemptIdResultadoRoute =
  AppSimuladosAttemptIdResultadoRouteImport.update({
    id: '/resultado',
    path: '/resultado',
    getParentRoute: () => AppSimuladosAttemptIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/cronograma': typeof AppCronogramaRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/plano': typeof AppPlanoRoute
  '/app/redacao': typeof AppRedacaoRoute
  '/app/': typeof AppIndexRoute
  '/app/materias/$slug': typeof AppMateriasSlugRoute
  '/app/simulados/$attemptId': typeof AppSimuladosAttemptIdRouteWithChildren
  '/app/materias/': typeof AppMateriasIndexRoute
  '/app/simulados/': typeof AppSimuladosIndexRoute
  '/app/simulados/$attemptId/resultado': typeof AppSimuladosAttemptIdResultadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/cronograma': typeof AppCronogramaRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/plano': typeof AppPlanoRoute
  '/app/redacao': typeof AppRedacaoRoute
  '/app': typeof AppIndexRoute
  '/app/materias/$slug': typeof AppMateriasSlugRoute
  '/app/simulados/$attemptId': typeof AppSimuladosAttemptIdRouteWithChildren
  '/app/materias': typeof AppMateriasIndexRoute
  '/app/simulados': typeof AppSimuladosIndexRoute
  '/app/simulados/$attemptId/resultado': typeof AppSimuladosAttemptIdResultadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/cronograma': typeof AppCronogramaRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/plano': typeof AppPlanoRoute
  '/app/redacao': typeof AppRedacaoRoute
  '/app/': typeof AppIndexRoute
  '/app/materias/$slug': typeof AppMateriasSlugRoute
  '/app/simulados/$attemptId': typeof AppSimuladosAttemptIdRouteWithChildren
  '/app/materias/': typeof AppMateriasIndexRoute
  '/app/simulados/': typeof AppSimuladosIndexRoute
  '/app/simulados/$attemptId/resultado': typeof AppSimuladosAttemptIdResultadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/app/cronograma'
    | '/app/perfil'
    | '/app/plano'
    | '/app/redacao'
    | '/app/'
    | '/app/materias/$slug'
    | '/app/simulados/$attemptId'
    | '/app/materias/'
    | '/app/simulados/'
    | '/app/simulados/$attemptId/resultado'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/cronograma'
    | '/app/perfil'
    | '/app/plano'
    | '/app/redacao'
    | '/app'
    | '/app/materias/$slug'
    | '/app/simulados/$attemptId'
    | '/app/materias'
    | '/app/simulados'
    | '/app/simulados/$attemptId/resultado'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/app/cronograma'
    | '/app/perfil'
    | '/app/plano'
    | '/app/redacao'
    | '/app/'
    | '/app/materias/$slug'
    | '/app/simulados/$attemptId'
    | '/app/materias/'
    | '/app/simulados/'
    | '/app/simulados/$attemptId/resultado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/redacao': {
      id: '/app/redacao'
      path: '/redacao'
      fullPath: '/app/redacao'
      preLoaderRoute: typeof AppRedacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plano': {
      id: '/app/plano'
      path: '/plano'
      fullPath: '/app/plano'
      preLoaderRoute: typeof AppPlanoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cronograma': {
      id: '/app/cronograma'
      path: '/cronograma'
      fullPath: '/app/cronograma'
      preLoaderRoute: typeof AppCronogramaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulados/': {
      id: '/app/simulados/'
      path: '/simulados'
      fullPath: '/app/simulados/'
      preLoaderRoute: typeof AppSimuladosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/materias/': {
      id: '/app/materias/'
      path: '/materias'
      fullPath: '/app/materias/'
      preLoaderRoute: typeof AppMateriasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulados/$attemptId': {
      id: '/app/simulados/$attemptId'
      path: '/simulados/$attemptId'
      fullPath: '/app/simulados/$attemptId'
      preLoaderRoute: typeof AppSimuladosAttemptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/materias/$slug': {
      id: '/app/materias/$slug'
      path: '/materias/$slug'
      fullPath: '/app/materias/$slug'
      preLoaderRoute: typeof AppMateriasSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulados/$attemptId/resultado': {
      id: '/app/simulados/$attemptId/resultado'
      path: '/resultado'
      fullPath: '/app/simulados/$attemptId/resultado'
      preLoaderRoute: typeof AppSimuladosAttemptIdResultadoRouteImport
      parentRoute: typeof AppSimuladosAttemptIdRoute
    }
  }
}

interface AppSimuladosAttemptIdRouteChildren {
  AppSimuladosAttemptIdResultadoRoute: typeof AppSimuladosAttemptIdResultadoRoute
}

const AppSimuladosAttemptIdRouteChildren: AppSimuladosAttemptIdRouteChildren = {
  AppSimuladosAttemptIdResultadoRoute: AppSimuladosAttemptIdResultadoRoute,
}

const AppSimuladosAttemptIdRouteWithChildren =
  AppSimuladosAttemptIdRoute._addFileChildren(
    AppSimuladosAttemptIdRouteChildren,
  )

interface AppRouteChildren {
  AppCronogramaRoute: typeof AppCronogramaRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPlanoRoute: typeof AppPlanoRoute
  AppRedacaoRoute: typeof AppRedacaoRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMateriasSlugRoute: typeof AppMateriasSlugRoute
  AppSimuladosAttemptIdRoute: typeof AppSimuladosAttemptIdRouteWithChildren
  AppMateriasIndexRoute: typeof AppMateriasIndexRoute
  AppSimuladosIndexRoute: typeof AppSimuladosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCronogramaRoute: AppCronogramaRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPlanoRoute: AppPlanoRoute,
  AppRedacaoRoute: AppRedacaoRoute,
  AppIndexRoute: AppIndexRoute,
  AppMateriasSlugRoute: AppMateriasSlugRoute,
  AppSimuladosAttemptIdRoute: AppSimuladosAttemptIdRouteWithChildren,
  AppMateriasIndexRoute: AppMateriasIndexRoute,
  AppSimuladosIndexRoute: AppSimuladosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
